import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "styles/Home.module.css";
import { CITIES } from "constants.js";
import InventoryTable from "components/InventoryTable";
import {
	TextField,
	Button,
	InputLabel,
	MenuItem,
	FormControl,
	Select,
} from "@mui/material";
import * as XLSX from "xlsx";
import axios from "axios";

export default function Home() {
	const [item, setItem] = useState("");
	const [stock, setStock] = useState(0);
	const [city, setCity] = useState(CITIES[0]);
	const [inventoryRows, setInventoryRows] = useState([]);

	useEffect(() => {
		const getData = async () => {
			const resp = await axios.get("/api/items");
			setInventoryRows(resp.data.items);
		};
		getData();
	}, []);

	const addToTable = () => {
		if (item === "" || city === "") {
			alert("Please Enter an Item");
			return;
		}
		axios
			.post("/api/items", {
				item: item,
				city,
				stock,
			})
			.then((successResp) => {
				setInventoryRows(successResp.data.items);
			})
			.catch((errResp) => {
				alert(errResp.response.data.msg);
			});
	};

	const exportToExcel = () => {
		const wb = XLSX.utils.book_new();
		const ws_name = "Inventory Data";

		/* make worksheet */
		// columns
		const ws_data = [["Item", "City", "Stock", "Weather"]];

		for (let i = 0; i < inventoryRows.length; ++i) {
			ws_data.push([
				inventoryRows[i].item,
				inventoryRows[i].city,
				inventoryRows[i].stock,
				inventoryRows[i].weather,
			]);
		}

		var ws = XLSX.utils.aoa_to_sheet(ws_data);
		/* Add the worksheet to the workbook */
		XLSX.utils.book_append_sheet(wb, ws, ws_name);

		const today = new Date();
		XLSX.writeFile(
			wb,
			`Inventory Data (${today.getFullYear()}-${
				today.getMonth() + 1
			}-${today.getDate()}).xlsx`
		);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Inventory Tracker</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/shopify.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Inventory Tracker</h1>
				<Button
					variant="outlined"
					onClick={() => exportToExcel()}
					sx={{ marginTop: "20px" }}
				>
					Export data to excel
				</Button>
				<div className={styles.textContainer}>
					<TextField
						className={styles.textField}
						id="item"
						label="Item"
						variant="standard"
						value={item}
						onChange={(e) => setItem(e.target.value.toLowerCase())}
					/>
					<TextField
						className={styles.textField}
						id="stock"
						label="Stock"
						variant="standard"
						value={stock}
						onChange={(e) => {
							if (!isNaN(e.target.value)) {
								setStock(e.target.value);
							}
						}}
					/>
					<FormControl sx={{ width: "200px", margin: "0 20px" }}>
						<InputLabel>City</InputLabel>
						<Select
							value={city}
							label="Age"
							onChange={(e) => setCity(e.target.value)}
						>
							{CITIES.map((city) => (
								<MenuItem value={city} key={city}>
									{city}
								</MenuItem>
							))}
						</Select>
					</FormControl>
					<Button variant="outlined" onClick={() => addToTable()}>
						Add to Table
					</Button>
				</div>
				<InventoryTable
					rows={inventoryRows}
					setRows={setInventoryRows}
				/>
			</main>
		</div>
	);
}
