import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "styles/Home.module.css";
import InventoryTable from "components/InventoryTable";
import { TextField, Button } from "@mui/material";
import axios from "axios";

export default function Home() {
	const [item, setItem] = useState("");
	const [city, setCity] = useState("");
	const [inventoryRows, setInventoryRows] = useState([]);

	useEffect(() => {
		const getData = async () => {
			const resp = await axios.get("/api/items");
			setInventoryRows(resp.data.items);
		};
		getData();
	}, []);

	const addToTable = () => {
		axios
			.post("/api/items", {
				item,
				city,
			})
			.then((successResp) => {
				setInventoryRows(successResp.data.items);
			})
			.catch((errResp) => {
				alert(errResp.response.data.msg);
			});
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Inventory Tracker</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				{/* <link rel="icon" href="/shop.png" /> */}
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Inventory Tracker</h1>
				<div className={styles.textContainer}>
					<TextField
						className={styles.textField}
						id="item"
						label="Item"
						variant="standard"
						value={item}
						onChange={(e) => setItem(e.target.value)}
					/>
					<TextField
						className={styles.textField}
						id="city"
						label="City"
						variant="standard"
						value={city}
						onChange={(e) => setCity(e.target.value)}
					/>
					<Button variant="outlined" onClick={() => addToTable()}>
						{" "}
						Add to Table
					</Button>
				</div>
				<InventoryTable
					rows={inventoryRows}
					setRows={setInventoryRows}
				/>
			</main>
		</div>
	);
}
