import Head from "next/head";
import styles from "styles/Home.module.css";
import InventoryTable from "components/InventoryTable";
import { TextField, Button } from "@mui/material";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Inventory Tracker</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				{/* <link rel="icon" href="/shop.png" /> */}
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Inventory Tracker</h1>
				<div className={styles.textContainer}>
					<TextField
						className={styles.textField}
						id="item"
						label="Item"
						variant="standard"
					/>
					<TextField
						className={styles.textField}
						id="city"
						label="City"
						variant="standard"
					/>
					<Button variant="outlined"> Add to Table</Button>
				</div>
				<InventoryTable />
			</main>
		</div>
	);
}
